#==============================#
#        Cognito              #
#==============================#
aws.cognito.region= ap-south-1
aws.cognito.clientId=xxxxx
#==============================#
#        Secret Manager          #
#==============================#
spring.aws.secretsManager.endpoint=yyyyy
spring.aws.secretsManager.region=ap-south-1

#==============================#
#        SES        #
#==============================#
ses.sender.email=abc@gmail.com


